// LAL-136 — CPA notice PDF (expiry / breach / demand). Not formal legal service.
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0';
import { jsPDF } from 'npm:jspdf@2.5.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

function json(status: number, body: Record<string, unknown>) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

function verifyServiceRole(authHeader: string, expectedKey: string): boolean {
  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token || !expectedKey || token.length !== expectedKey.length) return false;
  let diff = 0;
  for (let i = 0; i < token.length; i++) diff |= token.charCodeAt(i) ^ expectedKey.charCodeAt(i);
  return diff === 0;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  if (req.method !== 'POST') return json(405, { error: 'Method not allowed' });

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase = createClient(supabaseUrl, serviceKey);
  const authHeader = req.headers.get('Authorization') || '';
  const isCron = verifyServiceRole(authHeader, serviceKey);

  let callerId: string | null = null;
  if (!isCron) {
    const jwt = authHeader.replace(/^Bearer\s+/i, '');
    const {
      data: { user },
    } = await supabase.auth.getUser(jwt);
    if (!user) return json(401, { error: 'Unauthorized' });
    callerId = user.id;
  }

  const body = await req.json().catch(() => ({}));
  const leaseId = String(body.lease_id || '').trim();
  const kind = String(body.kind || '80');
  const noticeType = String(body.notice_type || 'expiry'); // expiry | breach | demand
  if (!leaseId) return json(400, { error: 'lease_id is required' });

  const { data: lease, error } = await supabase
    .from('leases')
    .select(
      'id, owner_id, tenant_id, end_date, monthly_rent, property:properties!property_id(title, address, city)'
    )
    .eq('id', leaseId)
    .single();
  if (error || !lease) return json(404, { error: 'Lease not found' });
  if (callerId && callerId !== lease.owner_id && callerId !== lease.tenant_id) {
    return json(403, { error: 'Not a party to this lease' });
  }

  const prop = (lease.property as { title?: string; address?: string; city?: string } | null) || {};
  const heading =
    noticeType === 'breach'
      ? 'CPA BREACH NOTICE'
      : noticeType === 'demand'
        ? 'FORMAL DEMAND FOR RENT'
        : `CPA s14 LEASE EXPIRY NOTICE (${kind} BUSINESS DAYS)`;

  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  doc.setFontSize(16);
  doc.text('LaLarente', 40, 50);
  doc.setFontSize(13);
  doc.text(heading, 40, 78);
  doc.setFontSize(10);
  const lines = [
    `Generated: ${new Date().toISOString()}`,
    `Property: ${prop.title || '—'}`,
    `Address: ${[prop.address, prop.city].filter(Boolean).join(', ') || '—'}`,
    `Lease ID: ${lease.id}`,
    `Lease end: ${lease.end_date}`,
    `Monthly rent: R ${Number(lease.monthly_rent || 0).toLocaleString('en-ZA')}`,
    '',
    'This PDF is generated by LaLarente as an in-app record of a Consumer Protection Act',
    'related notice (expiry window, arrears demand, or breach). It is NOT a substitute for',
    'formal legal service, sheriff delivery, or attorney-issued process. Keep a copy.',
  ];
  let y = 110;
  for (const line of lines) {
    doc.text(line, 40, y);
    y += 16;
  }

  const bytes = doc.output('arraybuffer');
  const path = `cpa/${lease.id}/${noticeType}-${kind}-${Date.now()}.pdf`;
  const { error: upErr } = await supabase.storage.from('work-orders').upload(path, bytes, {
    contentType: 'application/pdf',
    upsert: true,
  });
  if (upErr) {
    return json(500, { error: upErr.message, generated: true });
  }
  const { data: pub } = supabase.storage.from('work-orders').getPublicUrl(path);
  return json(200, {
    success: true,
    url: pub.publicUrl,
    path,
    disclaimer: 'Not formal legal service',
  });
});
