-- ============================================================
-- MIGRATION 056: Work Order completion reports (Plane #68)
-- ============================================================
-- When vendor work is completed, the generate-work-order-report
-- edge function renders a Work Order PDF (property header, per-area
-- work items table, before/after photos, 7-day declaration with
-- Agent + Tenant signature blocks, appendix) and emails it to the
-- Owner and Tenant.
--
-- The public URL is persisted here so BOTH parties can download the
-- report in-app (tenant reports + owner maintenance detail) and via
-- the emailed attachment. The bucket is PUBLIC (like receipts /
-- inspection-photos) so the download link works for both parties
-- without auth. Paths use the maintenance_request UUID, so links are
-- unguessable.
-- ============================================================

-- 1. Persist the report URL + email-sent timestamp on the request.
ALTER TABLE maintenance_requests
  ADD COLUMN IF NOT EXISTS work_order_report_url TEXT,
  ADD COLUMN IF NOT EXISTS work_order_report_sent_at TIMESTAMPTZ;

COMMENT ON COLUMN maintenance_requests.work_order_report_url IS
  'Public download URL of the Work Order completion report PDF (generated by generate-work-order-report on job completion).';
COMMENT ON COLUMN maintenance_requests.work_order_report_sent_at IS
  'Timestamp when the Work Order report email was sent to the Owner and Tenant.';

-- 2. Public work-orders bucket (PDF only, 10 MB cap).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('work-orders', 'work-orders', true, 10485760, ARRAY['application/pdf'])
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY['application/pdf'];

-- 3. Public read so the owner + tenant download links resolve.
--    Uploads are performed by the edge function with the service-role
--    key (RLS bypass), so no client upload policy is needed.
DROP POLICY IF EXISTS "Public can view work orders" ON storage.objects;
CREATE POLICY "Public can view work orders"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'work-orders');
