import { StyleSheet } from 'react-native';

const RSA = { green: '#007A4D', blue: '#002395' };

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#ffffff' },
  container: { flex: 1, backgroundColor: '#ffffff' },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  backButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  backIcon: { fontSize: 20, color: '#6b7280' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#111827' },
  cancelText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 100 },
  section: { marginBottom: 16 },
  label: { fontSize: 13, fontWeight: '600', color: '#374151', marginBottom: 6 },
  input: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: '#111827' },
  textArea: { minHeight: 80, textAlignVertical: 'top' },
  row: { flexDirection: 'row', gap: 12 },
  checkboxGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  checkboxColumn: { gap: 8, marginBottom: 12 },
  checkbox: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  checkboxBox: { width: 20, height: 20, borderRadius: 4, borderWidth: 2, borderColor: '#d1d5db', alignItems: 'center', justifyContent: 'center' },
  checkboxChecked: { backgroundColor: RSA.blue, borderColor: RSA.blue },
  checkmark: { color: '#ffffff', fontSize: 14, fontWeight: '700' },
  checkboxLabel: { fontSize: 13, color: '#374151' },
  customInputRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  addButton: { backgroundColor: RSA.blue, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  addButtonText: { fontSize: 13, fontWeight: '600', color: '#ffffff' },
  tagsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tag: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#dbeafe', borderWidth: 1, borderColor: '#3b82f6', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16 },
  tagText: { fontSize: 11, fontWeight: '600', color: '#1e40af' },
  tagClose: { fontSize: 16, fontWeight: '700', color: '#3b82f6' },
  submitButton: { backgroundColor: RSA.blue, paddingVertical: 16, borderRadius: 12, alignItems: 'center', marginTop: 8 },
  submitButtonDisabled: { opacity: 0.6 },
  submitButtonText: { fontSize: 16, fontWeight: '700', color: '#ffffff' },
  
  helperText: { fontSize: 12, color: '#6b7280', marginBottom: 8 },
  uploadButton: { backgroundColor: '#f3f4f6', borderWidth: 2, borderColor: '#e5e7eb', borderStyle: 'dashed', borderRadius: 12, paddingVertical: 20, alignItems: 'center', justifyContent: 'center' },
  uploadButtonText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  photosScroll: { marginTop: 12 },
  photoContainer: { position: 'relative', marginRight: 8 },
  photoPreview: { width: 100, height: 100, borderRadius: 8 },
  photoRemove: { position: 'absolute', top: -8, right: -8, width: 24, height: 24, borderRadius: 12, backgroundColor: '#ef4444', alignItems: 'center', justifyContent: 'center' },
  photoRemoveText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 12 },
  switchRow: { gap: 12 },
  switchItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#f9fafb', borderRadius: 12, marginBottom: 8 },
  switchLabel: { fontSize: 14, fontWeight: '600', color: '#374151' },
});
