import { StyleSheet } from 'react-native';

const RSA = {
  blue: '#002395',
  red: '#DE3831',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#ffffff' },
  container: { flex: 1, backgroundColor: '#f9fafb' },
  header: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#111827' },
  headerSubtitle: { fontSize: 13, fontWeight: '600', color: RSA.blue, marginTop: 2 },
  notificationInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  bellIcon: { fontSize: 18 },
  badge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: RSA.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { color: '#ffffff', fontSize: 10, fontWeight: '700' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 120 },

  // Loading, Error, and Empty States
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6b7280',
    marginTop: 16,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginTop: 16,
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 8,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: RSA.blue,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 24,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginTop: 16,
  },
  emptyMessage: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 8,
  },
  // ─── Above-fold primary CTA (Plane #81) ─────────────────────────────────────
  primaryCtaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFB81C',
    borderRadius: 14,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    gap: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  primaryCtaIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FFF7E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Hero affordance — a small uppercase eyebrow separates the single next-step
  // action from the Needs-attention list below (Plane #81 hero+detail restyle).
  primaryCtaEyebrow: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.1,
    // ~5.7:1 on #FFB81C (WCAG AA) — darker than #7A5A00 (~3.7:1) for 9px text.
    color: '#5A3E00',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  primaryCtaTitle: { fontSize: 15, fontWeight: '800', color: '#111827' },
  primaryCtaSub: { fontSize: 12, color: '#4B5563', marginTop: 2 },
  // ─── Needs-attention hub (Plane #81) ───────────────────────────────────────
  attentionHub: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 14,
  },
  attentionHubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  attentionHubTitle: { fontSize: 15, fontWeight: '700', color: '#111827' },
  // Frames the hub as the FULL list, complementing the single next-step CTA.
  attentionHubSub: { fontSize: 11, color: '#6B7280', marginTop: 1 },
  attentionHubBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: RSA.red,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  attentionHubBadgeText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  attentionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
  },
  attentionRowBorder: { borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  attentionRowIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attentionRowTitle: { fontSize: 13, fontWeight: '700', color: '#111827' },
  attentionRowSub: { fontSize: 11, color: '#6B7280', marginTop: 1 },
  // ─── Recently cancelled viewings (kept; not part of the hub) ───────────────
  cancellationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 8,
    gap: 10,
  },
  cancellationText: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
});
